##My Portofolio desktop
sarazaToussaint/My_portofolio pull request #2
Opened 2022-03-25 21:44 UTC by sarazaToussaint

In this project we:

- Add Makeup for desktop1
- Add animations 
- Add media queries

2022-03-25 23:27 UTC, Gambit142 requested changes
Hi @sarazaToussaint 👋, 

Good job so far!
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-25 23:27 UTC, Gambit142 commented on index.html
> +        <div class="about-div">
- [ ] For the _**About Myself**_ section, I would be recommending five changes that would help you make your portfolio look like that of the Figma template you chose:

1. The colour of the `h2` tag with text _**About Myself**_ should be `#091E42` and not black based on the template.
2. The height of the _**About Myself**_ aligned to the left should be a bit taller than that of the **_Languages_** aligned to the right. 
3. The `p` tag for description about yourself should not be more than 4-5 lines just like that of the template. Kindly work on that.
4. Your social media icons are not the same as that of the template and they are not evenly spread. It would be nice to fix that also.
5. The frameworks and skills on the right side below the languages are missing the dropdown icons. Kindly implement that.

### Your Design

![image](https://user-images.githubusercontent.com/77106962/160213502-5b966ff1-1711-493b-a1ad-ee38b378d705.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/160213551-8c1f6bd1-240a-44e9-88b2-c8909b3218d7.png)

#### Kindly implement all changes

2022-03-25 23:27 UTC, Gambit142 commented on style.css
> +  }
For this section, two changes need to be changed so that your design looks like that of the Figma template you choose.

1. The `p` tag that asks people if they have applications to build should be centred and not elongate the full width of the div. Kindly fix that.
2. The `button` tag with text _**Get In Touch**_ should be centred and not aligned to the right side. 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/160214112-5e2a68d6-6998-4978-95d1-b000e0df17b5.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/160214144-c75f9ba8-950d-4222-bdd6-39c1f36214c5.png)

#### It would be nice to consider reducing the background image: _**The arc**_ to the right. Kindly implement all changes 👍

2022-03-26 20:29 UTC, FrederickMih requested changes
Hi @sarazaToussaint , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-26 20:29 UTC, FrederickMih commented on index.html
>          <div class="works">
- [ ] You still needs to address some issues from line 198-226 in this work section in order to match the original design. The previous reviewer also touches on this section in his 2nd point. Your languages are not aligned to the left as seen in the original design. Also, make sure that the font-weight is the same as in Figma's design. Also, all the arrows are aligned to the right and are on a horizontal straight line. Please check the screenshots below and make sure that your design looks pretty much the same as in the Figma design. I also took some time to annotate so that you can have a bigger view of what is happening.


Your Implementation | Figma Design
:---:|:---:
![](https://user-images.githubusercontent.com/63087491/160255526-914fdc28-8f98-4551-a31a-d55a6b39195a.png) | ![](https://user-images.githubusercontent.com/63087491/160255529-ff2fb702-97ea-449c-b61d-142c56568b07.png)

- [ ] Also, make sure that the social media icons are evenly spread out as seen in the original design.

2022-03-26 21:42 UTC, AmaduKamara approved these changes
# Status: Approved 🟢

Hi @sarazaToussaint,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-26 21:42 UTC, AmaduKamara commented on index.html
>                <i class="fa fa-chevron-right" aria-hidden="true"></i>
[ Optional Changes ] These changes won't stop your project from being approved but will help improve your design and help you become a better developer. I kindly recommend you consider implementing them and make your design look great 🤝

- [ ] Kindly adjust these changes marked as optional to improve your design and match the one in Figma
- [ ] From the screenshots below, please make the left `div` have `40%` width and the right `60%` width
- [ ] Also consider moving the `fa-chevron-right` to the right order where I marked with the red arrow. 👍 

** Your Design**

![image](https://user-images.githubusercontent.com/50941074/160257941-20998480-a3a6-4209-b4fd-5d90a46a4781.png)

** The Figma Design**
![image](https://user-images.githubusercontent.com/50941074/160258083-8b9f1a81-757b-4b04-862c-6ece17ad725a.png)

2022-03-28 15:14 UTC, merged