##Feature mobile menu
sarazaToussaint/My_portofolio pull request #5
Opened 2022-04-05 16:36 UTC by sarazaToussaint

In this project we:

> Add Eslint in our repo
> Add index.js file to make our hamburger button work once a user clicks on it
> Add codes in makeup and stylesheet files for the mobile menu

2022-04-05 18:02 UTC, ShadyShawkat requested changes
## Hi @sarazaToussaint, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Kindly make sure to add the `MIT` License and the link to it in your `README.md`, you can see it [here](https://github.com/microverseinc/readme-template).
- [ ] _Check the comments under the review for more changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 18:02 UTC, ShadyShawkat commented on index.js
> +};
- [ ] [OPTIONAL] Please make sure to use `ES6` arrow functions instead of the `function` keyword, which is considered good practice.

2022-04-06 07:57 UTC, sarazaToussaint commented
I made the required changes except changing the functions to the arrows function which is optional. 
Thank you for the review

2022-04-06 08:13 UTC, Mre55 approved these changes
**Hi @sarazaToussaint,**

# Status: APPROVED 🎉  💪 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

![Alt Text](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 08:25 UTC, merged